version: "3"
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:80"
