version: "3"
services:
  backend:
    image: portfolio-backend
    build: ./api-resume
    container_name: portfolio-backend
    restart: always
    env_file:
      - ./api-resume/.env
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - portfolio-net

  frontend:  
    image: portfolio-frontend
    build: ./app-resume
    container_name: portfolio-frontend
    restart: always
    env_file:
      - ./app-resume/.env
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - portfolio-net
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=portfolio.jarasite.com
      - LETSENCRYPT_HOST=portfolio.jarasite.com
      - LETSENCRYPT_EMAIL=moncalvillo.pablo@gmail.com

networks:
  nginx-proxy:
    external: true
  portfolio-net:
    external: false
  
