version: "3"
services:
  backend:
    build: ./api-resume
    container_name: backend
    restart: always
    env_file:
      - ./api-resume/.env
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - portfolio-net

  frontend:
    build: ./app-resume
    container_name: frontend
    restart: always
    env_file:
      - ./app-resume/.env
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - portfolio-net

networks:
  portfolio-net:
    external: true
